<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Fundamentos Estadísticos con R - 1&nbsp; Summary (resumen) Estadística</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./intro.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Summary (resumen) Estadística</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fundamentos Estadísticos con R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Summary (resumen) Estadística</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Números aleatorios y Probabilidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Teorema_LC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Más Distribuciones y el Teorema del Límite Central</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlacion_de.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Correlación y Diseño Experimental</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#qué-es-la-estadística" id="toc-qué-es-la-estadística" class="nav-link active" data-scroll-target="#qué-es-la-estadística"><span class="header-section-number">1.1</span> ¿Qué es la estadística ?</a>
  <ul class="collapse">
  <li><a href="#qué-pueden-hacer-las-estadísticas" id="toc-qué-pueden-hacer-las-estadísticas" class="nav-link" data-scroll-target="#qué-pueden-hacer-las-estadísticas"><span class="header-section-number">1.1.1</span> ¿Qué pueden hacer las estadísticas?</a></li>
  <li><a href="#qué-no-pueden-hacer-las-estadísticas" id="toc-qué-no-pueden-hacer-las-estadísticas" class="nav-link" data-scroll-target="#qué-no-pueden-hacer-las-estadísticas"><span class="header-section-number">1.1.2</span> ¿Qué no pueden hacer las estadísticas?</a></li>
  <li><a href="#tipos-de-estadísticas" id="toc-tipos-de-estadísticas" class="nav-link" data-scroll-target="#tipos-de-estadísticas"><span class="header-section-number">1.1.3</span> Tipos de Estadísticas</a></li>
  <li><a href="#tipos-de-datos" id="toc-tipos-de-datos" class="nav-link" data-scroll-target="#tipos-de-datos"><span class="header-section-number">1.1.4</span> Tipos de Datos</a></li>
  <li><a href="#los-datos-categóricos-se-pueden-presentar-como-números" id="toc-los-datos-categóricos-se-pueden-presentar-como-números" class="nav-link" data-scroll-target="#los-datos-categóricos-se-pueden-presentar-como-números"><span class="header-section-number">1.1.5</span> Los datos categóricos se pueden presentar como números</a></li>
  <li><a href="#por-qué-es-importante-el-tipo-de-dato" id="toc-por-qué-es-importante-el-tipo-de-dato" class="nav-link" data-scroll-target="#por-qué-es-importante-el-tipo-de-dato"><span class="header-section-number">1.1.6</span> ¿Por qué es importante el tipo de dato?</a></li>
  </ul></li>
  <li><a href="#medidas-del-centro" id="toc-medidas-del-centro" class="nav-link" data-scroll-target="#medidas-del-centro"><span class="header-section-number">1.2</span> Medidas del Centro</a>
  <ul class="collapse">
  <li><a href="#datos-de-sueño-de-mamiferos" id="toc-datos-de-sueño-de-mamiferos" class="nav-link" data-scroll-target="#datos-de-sueño-de-mamiferos"><span class="header-section-number">1.2.1</span> Datos de sueño de mamiferos</a></li>
  <li><a href="#cuánto-tiempo-suelen-dormir-los-mamíferos-de-este-conjunto-de-datos" id="toc-cuánto-tiempo-suelen-dormir-los-mamíferos-de-este-conjunto-de-datos" class="nav-link" data-scroll-target="#cuánto-tiempo-suelen-dormir-los-mamíferos-de-este-conjunto-de-datos"><span class="header-section-number">1.2.2</span> ¿Cuánto tiempo suelen dormir los mamíferos de este conjunto de datos ?</a></li>
  </ul></li>
  <li><a href="#medidas-del-centro-1" id="toc-medidas-del-centro-1" class="nav-link" data-scroll-target="#medidas-del-centro-1"><span class="header-section-number">1.3</span> Medidas del Centro</a>
  <ul class="collapse">
  <li><a href="#media" id="toc-media" class="nav-link" data-scroll-target="#media"><span class="header-section-number">1.3.1</span> Media</a></li>
  <li><a href="#mediana" id="toc-mediana" class="nav-link" data-scroll-target="#mediana"><span class="header-section-number">1.3.2</span> Mediana</a></li>
  <li><a href="#la-moda" id="toc-la-moda" class="nav-link" data-scroll-target="#la-moda"><span class="header-section-number">1.3.3</span> La Moda</a></li>
  </ul></li>
  <li><a href="#agregar-un-valor-atípico" id="toc-agregar-un-valor-atípico" class="nav-link" data-scroll-target="#agregar-un-valor-atípico"><span class="header-section-number">1.4</span> Agregar un valor atípico</a></li>
  <li><a href="#sesgo" id="toc-sesgo" class="nav-link" data-scroll-target="#sesgo"><span class="header-section-number">1.5</span> Sesgo</a></li>
  <li><a href="#ejercicio-1" id="toc-ejercicio-1" class="nav-link" data-scroll-target="#ejercicio-1"><span class="header-section-number">1.6</span> Ejercicio 1</a></li>
  <li><a href="#ejercicio-2" id="toc-ejercicio-2" class="nav-link" data-scroll-target="#ejercicio-2"><span class="header-section-number">1.7</span> Ejercicio 2</a></li>
  <li><a href="#medidas-de-propagación" id="toc-medidas-de-propagación" class="nav-link" data-scroll-target="#medidas-de-propagación"><span class="header-section-number">1.8</span> Medidas de Propagación</a>
  <ul class="collapse">
  <li><a href="#qué-es-spread" id="toc-qué-es-spread" class="nav-link" data-scroll-target="#qué-es-spread"><span class="header-section-number">1.8.1</span> ¿Qué es Spread?</a></li>
  <li><a href="#la-varianza" id="toc-la-varianza" class="nav-link" data-scroll-target="#la-varianza"><span class="header-section-number">1.8.2</span> La Varianza</a></li>
  </ul></li>
  <li><a href="#desviación-estándar" id="toc-desviación-estándar" class="nav-link" data-scroll-target="#desviación-estándar"><span class="header-section-number">1.9</span> Desviación Estándar</a>
  <ul class="collapse">
  <li><a href="#desviación-absoluta-media" id="toc-desviación-absoluta-media" class="nav-link" data-scroll-target="#desviación-absoluta-media"><span class="header-section-number">1.9.1</span> Desviación Absoluta Media</a></li>
  <li><a href="#cuartiles" id="toc-cuartiles" class="nav-link" data-scroll-target="#cuartiles"><span class="header-section-number">1.9.2</span> Cuartiles</a></li>
  <li><a href="#gráficas-de-caja-usan-cuartiles" id="toc-gráficas-de-caja-usan-cuartiles" class="nav-link" data-scroll-target="#gráficas-de-caja-usan-cuartiles"><span class="header-section-number">1.9.3</span> Gráficas de caja usan cuartiles</a></li>
  <li><a href="#cuantiles" id="toc-cuantiles" class="nav-link" data-scroll-target="#cuantiles"><span class="header-section-number">1.9.4</span> Cuantiles</a></li>
  </ul></li>
  <li><a href="#rango-intercuartilico-iqr" id="toc-rango-intercuartilico-iqr" class="nav-link" data-scroll-target="#rango-intercuartilico-iqr"><span class="header-section-number">1.10</span> Rango Intercuartilico (IQR)</a>
  <ul class="collapse">
  <li><a href="#valores-atípicos" id="toc-valores-atípicos" class="nav-link" data-scroll-target="#valores-atípicos"><span class="header-section-number">1.10.1</span> Valores atípicos</a></li>
  <li><a href="#encontrar-valores-atípicos" id="toc-encontrar-valores-atípicos" class="nav-link" data-scroll-target="#encontrar-valores-atípicos"><span class="header-section-number">1.10.2</span> Encontrar valores atípicos</a></li>
  </ul></li>
  <li><a href="#ejercicio-3" id="toc-ejercicio-3" class="nav-link" data-scroll-target="#ejercicio-3"><span class="header-section-number">1.11</span> Ejercicio 3</a></li>
  <li><a href="#ejercicio-4" id="toc-ejercicio-4" class="nav-link" data-scroll-target="#ejercicio-4"><span class="header-section-number">1.12</span> Ejercicio 4</a></li>
  <li><a href="#ejercicio-5" id="toc-ejercicio-5" class="nav-link" data-scroll-target="#ejercicio-5"><span class="header-section-number">1.13</span> Ejercicio 5</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Summary (resumen) Estadística</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Las estadísticas de resumen (summary) le brindan las herramientas que necesita para reducir conjuntos de datos masivos para revelar los aspectos más destacados. En este capítulo, explorará estadísticas resumidas, incluidas la media, mediana y desviación estándar, y aprenderá a interpretarlas con precisión. También desarrollará sus habilidades de pensamiento crítico, lo que le permitirá las mejores estadísticas de resumen para sus datos.</p>
<section id="qué-es-la-estadística" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="qué-es-la-estadística"><span class="header-section-number">1.1</span> ¿Qué es la estadística ?</h2>
<p>Es la práctica y el estudio de la recopilación y el análisis de datos. También podemos hablar de una estadística de resumen, que es un hecho o un resumen de algunos datos, como un promedio o un conteo.</p>
<section id="qué-pueden-hacer-las-estadísticas" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="qué-pueden-hacer-las-estadísticas"><span class="header-section-number">1.1.1</span> ¿Qué pueden hacer las estadísticas?</h3>
<p>on el poder de las estadísticas, podemos responder toneladas de preguntas diferentes como: ¿Qué tan probable es que alguien compre un producto? ¿Es más probable que las personas lo compren si pueden usar un sistema de pago diferente? ¿Cuántos ocupantes tendrá su hotel? ¿Cómo se puede optimizar la ocupación? ¿Cuántas tallas de jeans deben fabricarse para que le queden al 95% de la población? ¿Se debe producir el mismo número de cada tamaño? Una pregunta como, ¿Qué anuncio es más eficaz para que la gente compre un producto? Se puede responder con pruebas A/B</p>
</section>
<section id="qué-no-pueden-hacer-las-estadísticas" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="qué-no-pueden-hacer-las-estadísticas"><span class="header-section-number">1.1.2</span> ¿Qué no pueden hacer las estadísticas?</h3>
<p>Si bien las estadísticas pueden responder muchas preguntas, es importante tener en cuenta que las estadísticas no pueden responder todas las preguntas. Si queremos saber por qué la serie de TV Game of Thrones es tan popular, podríamos preguntar a todos por qué les gusta, pero pueden mentir o dejar de lado las razones. Podemos ver si las series con escenas más violentas atraen a más espectadores, pero incluso si lo hacen, no podemos saber si la violencia en Game of Throne es la razón de su popularidad, o si otros factores están impulsando su popularidad y simplemente sucede.</p>
</section>
<section id="tipos-de-estadísticas" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="tipos-de-estadísticas"><span class="header-section-number">1.1.3</span> Tipos de Estadísticas</h3>
<p>Hay dos ramas principales de la estadística:</p>
<ul>
<li><p>Estadística Descriptiva</p></li>
<li><p>Estadística Inferencial</p></li>
</ul>
<section id="estadística-descriptiva" class="level4" data-number="1.1.3.1">
<h4 data-number="1.1.3.1" class="anchored" data-anchor-id="estadística-descriptiva"><span class="header-section-number">1.1.3.1</span> Estadística Descriptiva</h4>
<p>Este tipo de estadística se centra en describir y resumir los datos disponibles. Después de preguntar a cuatro amigos cómo llegan al trabajo, podemos ver que el 50% de ellos conducen al trabajo, el 25% van en autobús y el 25% en bicicleta. Estos son ejemplos de estadísticas descriptivas.</p>
</section>
<section id="estadística-inferencial" class="level4" data-number="1.1.3.2">
<h4 data-number="1.1.3.2" class="anchored" data-anchor-id="estadística-inferencial"><span class="header-section-number">1.1.3.2</span> Estadística Inferencial</h4>
<p>Este tipo de estadística utiliza los datos disponibles, que se denominan datos de muestra, para hacer inferencia sobre una población más grande. Podríamos usar estadísticas inferenciasles para determinar que porcentaje de personas conducen al trabajo en función de nuestros datos de muestra.</p>
</section>
</section>
<section id="tipos-de-datos" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="tipos-de-datos"><span class="header-section-number">1.1.4</span> Tipos de Datos</h3>
<p>Existen dos tipos principales de datos. Los datos númericos o cuantitativos se componen de valores numéricos. Los datos categóricos o cualitativos están formados por valores que pertenecen a distintos grupos. Es importante tener en cuenta que estos no son los únicos tipos de datos que existen; también hay otros, pero nos centraremos en estos dos. Los datos numéricos se pueden separar en datos:</p>
<ul>
<li><p>continuos, y</p></li>
<li><p>discretos.</p></li>
</ul>
<p>Los datos <code>numéricos continuos</code> suelen ser cantidades que pueden medir, como la velocidad o el tiempo. Los datos <code>numéricos discretos</code> suelen ser datos de conteo, como la cantidad de mascotas o la cantidad de paquetes enviados. Los datos categóricos pueden ser nominales o ordinales.</p>
<ul>
<li><p>Los datos categóricos nominales se componen de categorías sin orden inherente, como el estado civil o el país de residencia.</p></li>
<li><p>Los datos categóricos ordinales tienen un orden inherente, como una una pregunta de encuesta donde debe indicar el grado en que está de acuerdo con una afirmación.</p></li>
</ul>
</section>
<section id="los-datos-categóricos-se-pueden-presentar-como-números" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="los-datos-categóricos-se-pueden-presentar-como-números"><span class="header-section-number">1.1.5</span> Los datos categóricos se pueden presentar como números</h3>
<p>A veces, las variables categóricas se representan mediante números. Los casados y solteros se pueden representar usando 1 y 0, o una escala del 1 al 5. Sin embargo es importante tener en cuenta que esto no necesariamente los convierte en variables númericas.</p>
</section>
<section id="por-qué-es-importante-el-tipo-de-dato" class="level3" data-number="1.1.6">
<h3 data-number="1.1.6" class="anchored" data-anchor-id="por-qué-es-importante-el-tipo-de-dato"><span class="header-section-number">1.1.6</span> ¿Por qué es importante el tipo de dato?</h3>
<p>Ser capaz de identificar los tipos de datos es importante, ya que el tipo de datos con los que está trabajando dictará qué tipos de estadística de resumen y visualizaciones tienen sentido para sus datos, por lo que esta es una habilidad importante que debe dominar. Para datos numericós, podemos usar estadísticas de resumen como la media y gráficos como diagramas de dispersión, pero estos no tienen mucho sentido para los datos categóricos.</p>
<p>Veamos el siguiente ejemplo, para comenzar a diferenciar la estadística descriptiva de la inferencial</p>
<table class="table">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Descriptiva</th>
<th>Inferencial</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Teniendo en cuenta los datos de cada solicitud de sevicio al cliente realizada, ¿Cuál es el tiempo promedio que se tardo en responder?</td>
<td>Después de entrevistar a 100 clientes, ¿Qué porcentaje de todos sus clientes está satisfecho con su producto?</td>
</tr>
<tr class="even">
<td>Dados los datos de las 100,000 personas que vieron el anuncio ¿Qué porcentaje de personas hizo click en el?</td>
<td>Dados los datos de 20 peces capturados en un lago, ¿cuál es el peso promedio de todos los peces del lago?</td>
</tr>
</tbody>
</table>
<p>Ahora, hagamos un ejercicio similar para identificar el tipo de dato.</p>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 40%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>numérico (continuo)</th>
<th>numérico (discreto)</th>
<th>categórico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kilovatios de electricidad utilizados</td>
<td>Número de cursos de estadística tomados</td>
<td>Marca de un producto</td>
</tr>
<tr class="even">
<td>Temperatura del aire</td>
<td>Número de artículos en Stock</td>
<td>Código Postal</td>
</tr>
<tr class="odd">
<td></td>
<td>Número de click en un anuncio</td>
<td></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="medidas-del-centro" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="medidas-del-centro"><span class="header-section-number">1.2</span> Medidas del Centro</h2>
<p>En esta sección, comenzaremos a analizar las estadísticas de resumen, algunas de las cuales quizás ya le resulten familiares, como la <code>media</code> y la <code>mediana</code>.</p>
<section id="datos-de-sueño-de-mamiferos" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="datos-de-sueño-de-mamiferos"><span class="header-section-number">1.2.1</span> Datos de sueño de mamiferos</h3>
<p>Veremos los datos sobre los hábitos de sueño de diferentes mamíferos. Estos datos ya estan precargados por defecto en <code>R</code> en el paquete o librería de <code>ggplot2</code>, veamos como acceder a ellos en R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)  </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"msleep"</span>) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>msleep</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 83 × 11
   name   genus vore  order conservation sleep_total sleep_rem sleep_cycle awake
   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
 1 Cheet… Acin… carni Carn… lc                  12.1      NA        NA      11.9
 2 Owl m… Aotus omni  Prim… &lt;NA&gt;                17         1.8      NA       7  
 3 Mount… Aplo… herbi Rode… nt                  14.4       2.4      NA       9.6
 4 Great… Blar… omni  Sori… lc                  14.9       2.3       0.133   9.1
 5 Cow    Bos   herbi Arti… domesticated         4         0.7       0.667  20  
 6 Three… Brad… herbi Pilo… &lt;NA&gt;                14.4       2.2       0.767   9.6
 7 North… Call… carni Carn… vu                   8.7       1.4       0.383  15.3
 8 Vespe… Calo… &lt;NA&gt;  Rode… &lt;NA&gt;                 7        NA        NA      17  
 9 Dog    Canis carni Carn… domesticated        10.1       2.9       0.333  13.9
10 Roe d… Capr… herbi Arti… lc                   3        NA        NA      21  
# ℹ 73 more rows
# ℹ 2 more variables: brainwt &lt;dbl&gt;, bodywt &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Antes de sumerginos en esto, recordemos cómo funcionan los histogramas. Un histograma toma un montón de puntos de datos y los separa en contenedores o rangos de valores.</p>
<p><img src="fig2.png" class="img-fluid"></p>
<p>Aquí hay un contenedor de 0 a 2 horas, de 2 a 4 horas y así sucesivamente. Las alturas de las barras representan las cantidad de puntos de datos que caen en ese contenedor, por lo que hay un mamífero en el conjunto de datos que duerme entre 0 y 2 horas, y nueve mamíferos que duermen de dos a cuatro horas. Los histogramas son una excelente manera de resumir visualmente los datos, pero podemos usar estadísticas de resumen numérico para resumir aún más.</p>
</section>
<section id="cuánto-tiempo-suelen-dormir-los-mamíferos-de-este-conjunto-de-datos" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="cuánto-tiempo-suelen-dormir-los-mamíferos-de-este-conjunto-de-datos"><span class="header-section-number">1.2.2</span> ¿Cuánto tiempo suelen dormir los mamíferos de este conjunto de datos ?</h3>
<p><img src="fig3.png" class="img-fluid"></p>
<p>Una forma de resumir los datos es respondiendo a la pregunta de esta sección. Para responder a esto, necesitamos averiguar cuál es el valor <code>típico</code> o <code>central</code> de los datos. Discutiremos tres definiciones diferentes, o medidas de centro:</p>
<ol type="1">
<li>Media</li>
<li>Mediana</li>
<li>Moda</li>
</ol>
</section>
</section>
<section id="medidas-del-centro-1" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="medidas-del-centro-1"><span class="header-section-number">1.3</span> Medidas del Centro</h2>
<section id="media" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="media"><span class="header-section-number">1.3.1</span> Media</h3>
<p>La media, a menudo llamada promedio, es una de las formas más comunes de resumir los datos. Para calcular la media, sumamos todos los números de interés y los dividimos por el número total de puntos de datos, que aquí es 83.</p>
<p><span class="math display">\[
media = \bar{x} = \frac{1}{n}\sum_{i=1}^n x_i
\]</span></p>
<p>Esto nos da 10 punto 43 horas de sueño. En <code>R</code>, podemos usar la función <code>mean()</code> pasándole la variable de interés.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(msleep<span class="sc">$</span>sleep_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.43373</code></pre>
</div>
</div>
</section>
<section id="mediana" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="mediana"><span class="header-section-number">1.3.2</span> Mediana</h3>
<p>Otra medida de centro es la mediana. La mediana es el valor en el que el 50% de los datos es inferior y el 50% de los datos es superior. Podemos calcular esto ordenando todos los puntos de datos y tomando el del medio, que sería el indice 42 en este caso.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(msleep<span class="sc">$</span>sleep_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1.9  2.7  2.9  3.0  3.1  3.3  3.5  3.8  3.9  4.0  4.4  5.2  5.3  5.3  5.4
[16]  5.6  6.2  6.3  6.3  7.0  7.7  8.0  8.3  8.4  8.4  8.6  8.7  8.7  8.9  9.1
[31]  9.1  9.4  9.4  9.5  9.6  9.7  9.8  9.8 10.0 10.1 10.1 10.1 10.3 10.3 10.4
[46] 10.6 10.9 11.0 11.0 11.1 11.3 11.5 12.1 12.5 12.5 12.5 12.5 12.8 12.8 13.0
[61] 13.5 13.7 13.8 14.2 14.3 14.4 14.4 14.5 14.6 14.9 14.9 15.6 15.8 15.8 15.9
[76] 16.6 17.0 17.4 18.0 18.1 19.4 19.7 19.9</code></pre>
</div>
</div>
<p>Esto nos da una mediana de 10.1 horas de sueño.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(msleep<span class="sc">$</span>sleep_total)[<span class="dv">42</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.1</code></pre>
</div>
</div>
<p>En R, podemos usar la función <code>median()</code> para hacer los cálculos por nosotros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(msleep<span class="sc">$</span>sleep_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.1</code></pre>
</div>
</div>
</section>
<section id="la-moda" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="la-moda"><span class="header-section-number">1.3.3</span> La Moda</h3>
<p>La moda es el valor más frecuente en los datos. Si contamos cuantas ocurrencias hay dentro de cada <code>sleep_total</code> y ordenamos en orden descendente, veamos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ lubridate 1.9.2     ✔ tibble    3.2.1
✔ purrr     1.0.1     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>msleep <span class="sc">%&gt;%</span> <span class="fu">count</span>(sleep_total, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 65 × 2
   sleep_total     n
         &lt;dbl&gt; &lt;int&gt;
 1        12.5     4
 2        10.1     3
 3         5.3     2
 4         6.3     2
 5         8.4     2
 6         8.7     2
 7         9.1     2
 8         9.4     2
 9         9.8     2
10        10.3     2
# ℹ 55 more rows</code></pre>
</div>
</div>
<p>note que hay 4 mamiferos que duermen durante 12.5 horas, así que esta es la moda. La moda de la variable <code>vore</code> del conjunto de datos, que indica la dieta del animal es herbívora, veamomos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>msleep <span class="sc">%&gt;%</span> <span class="fu">count</span>(vore, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  vore        n
  &lt;chr&gt;   &lt;int&gt;
1 herbi      32
2 omni       20
3 carni      19
4 &lt;NA&gt;        7
5 insecti     5</code></pre>
</div>
</div>
<p>La moda se usa a menudo para variables categóricas, ya que las variables categóricas, pueden estar desordenadas y, a menudo no tienen una representación numérica inherente.</p>
</section>
</section>
<section id="agregar-un-valor-atípico" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="agregar-un-valor-atípico"><span class="header-section-number">1.4</span> Agregar un valor atípico</h2>
<p>Ahora que tenemos muchas formas de medir el centro, ¿cómo sabemos cuál usar? Veamos un ejemplo. Aquí, tenemos todos los insectivoros en el conjunto de datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>msleep <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(vore <span class="sc">==</span> <span class="st">"insecti"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_sleep =</span> <span class="fu">mean</span>(sleep_total),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_sleep =</span> <span class="fu">median</span>(sleep_total))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_sleep median_sleep
       &lt;dbl&gt;        &lt;dbl&gt;
1       14.9         18.1</code></pre>
</div>
</div>
<p>Obtenemos un tiempo de sueño medio de 14.94 horas y un tiempo de sueño medio de 18.1 horas.</p>
<p>Ahora digamos que hemos descubierto un nuevo insectívoro misterioso que nunca duerme.</p>
<p>Si volvemos a tomar la media y mediana, obtenemos resultados diferentes. La media se puede reducir en más de 3 horas, mientras que la mediana cambió en menos de una hora. Esto se debe a que la media es mucho más sensible a los valores extremos que la mediana.</p>
<p>Dado que la media es más sensible a los valores extremos, funciona mejor para datos simétricos como este.</p>
<p><img src="fig4.png" class="img-fluid"></p>
<p>Observe que la media, en rojo, y la mediana en verde, estan bastante cerca.</p>
</section>
<section id="sesgo" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sesgo"><span class="header-section-number">1.5</span> Sesgo</h2>
<p>Sin embargo, si los datos estan sesgados, lo que significa que no son simétricos, como se muestra en la figura siguiente</p>
<p><img src="fig5.png" class="img-fluid"></p>
<p>generalmente es mejor usar la mediana. En este histograma, note que los datos se apilan a la derecha. Los datos que se ven así se denominan datos asimétricos a la izquierda. Cuando los datos se acumulan a la izquierda, están sesgados a la derecha, vea la siguiente figura.</p>
<p><img src="fig6.png" class="img-fluid"></p>
<p>Cuando los datos están sesgados, la media y la mediana son diferentes. La media se tira en dirección del sesgo, por lo que es más baja que la mediana en los datos sesgados a la izquierda y más alta que la mediana en los datos sesgados a la derecha.</p>
<p><img src="fig7.png" class="img-fluid"></p>
<p>Debido a que la media se ve afectada por los valores extremos, es mejor usar la mediana, ya que se ve menos afectada por los valores atípicos.</p>
</section>
<section id="ejercicio-1" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="ejercicio-1"><span class="header-section-number">1.6</span> Ejercicio 1</h2>
<p>En este capítulo, trabajaremos con el indice de huella de carbono alimentario 2018. El conjunto de datos <code>food_consumption</code> contiene información sobre los kilogramos de alimentos consumidos por persona por año en cada país en cada categoría de alimentos (<code>consumption)</code>, así como información sobre la huella de carbono de esa categoría de alimentos (<code>co2_emissions</code>) medida en kilogramos de dióxido de carbono o <span class="math inline">\(CO_2\)</span>, por persona por año en cada país.</p>
<p>En este ejercicio, nos encargaremos de calcular medidas de centro para comparar el consumo de alimentos en EE.UU y Bélgica.</p>
<ul>
<li>Primero creamos dos marcos de datos: uno que contenga las filas de <code>food_consumption</code> para <code>Bélgica</code> y otro que contenga las filas de <code>USA</code>. Llamaremos a estos marcos de datos como <code>belgica_consumption</code> y <code>usa_consumption</code>. Veamos como hacerlo en R.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Primero cargamos el conjunto de datos</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>food_consumption <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"food_consumption.rds"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>belgica_consumption <span class="ot">&lt;-</span> food_consumption <span class="sc">%&gt;%</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"Belgium"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>usa_consumption <span class="ot">&lt;-</span> food_consumption <span class="sc">%&gt;%</span> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"USA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora, calculamos la media y mediana de kilogramos de alimentos consumidos por persona por año para ambos países.</p>
<ul>
<li><strong><em>Bélgica</em></strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(belgica_consumption<span class="sc">$</span>consumption)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 42.13273</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(belgica_consumption<span class="sc">$</span>consumption)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.59</code></pre>
</div>
</div>
<ul>
<li><strong><em>Usa</em></strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(usa_consumption<span class="sc">$</span>consumption)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.65</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(usa_consumption<span class="sc">$</span>consumption)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.58</code></pre>
</div>
</div>
<p>Po último, filtremos food_consumption por filas con datos sobre Bélgica y EE.UU. Agruparemos los datos filtrados por país (country). Calcularemos la media y mediana de los kilogramos de alimentos consumidos por persona al año en cada país. Llame a estas columnas <code>mean_consumption</code> y <code>median_consumption</code>. Veamos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>food_consumption <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filtramops para Belgium and USA</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Belgium"</span>, <span class="st">"USA"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># agrupamos por pais (country)</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Obtenemos resumen de consumo medio y mediano.</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_consumption =</span> <span class="fu">mean</span>(consumption),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">median_consumption =</span> <span class="fu">median</span>(consumption))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  country mean_consumption median_consumption
  &lt;chr&gt;              &lt;dbl&gt;              &lt;dbl&gt;
1 Belgium             42.1               12.6
2 USA                 44.6               14.6</code></pre>
</div>
</div>
</section>
<section id="ejercicio-2" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="ejercicio-2"><span class="header-section-number">1.7</span> Ejercicio 2</h2>
<p>En esta sección, usted aprendio que la media es la suma de todos los puntos de datos dividida por el número total de puntos de datos , y que la mediana es el valor medio del conjunto de datos donde el 50% de los datos es menor que la mediana y 50% de los datos es mayor que la mediana. En este ejercicio, comparará estas dos medidas del centro.</p>
<p>Para ello usaremos el paquete <code>ggplot2</code> que nos facilita la creación de gráficos.</p>
<p>Primero, filtramos f<code>ood_consumption</code> para obtener las filas donde <code>food_category</code> está <code>rice.</code></p>
<p>Segundo, cree un histograma usando <code>ggplot2</code> de co2_emission para el arroz (rice)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>food_consumption <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filter for rice food category</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(food_category <span class="sc">==</span> <span class="st">"rice"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create histogram of co2_emission</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(co2_emission)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="intro_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Mire el histograma para el arroz (rice) que acabamos de calcular. ¿Cuál de los siguientes terminos describe mejor los datos?</p>
<ul>
<li><p>Sin sesgo</p></li>
<li><p>Sesgado a la izquierda</p></li>
<li><p>Sesgado a la derecha</p></li>
</ul>
<p>Viendo el gráfico, claramento los datos están sesgado a la derecha.</p>
<p>En este mismo ejercicio hagamos algo más. Filtremos <code>food_consumption</code> para obtener las filas donde <code>food_category</code> está <code>rice</code>.</p>
<p>Luego, resumiremos los datos para obtener la media y la mediana de <code>co2_emission</code>, llamándolos <code>mean_co2</code> y <code>median_co2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>food_consumption <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filtramos por categoría de alimentos de arroz</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(food_category <span class="sc">==</span> <span class="st">"rice"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># obtenemos mean_co2 and median_co2</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_co2 =</span> <span class="fu">mean</span>(co2_emission),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_co2 =</span> <span class="fu">median</span>(co2_emission))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_co2 median_co2
     &lt;dbl&gt;      &lt;dbl&gt;
1     37.6       15.2</code></pre>
</div>
</div>
<p>Dada la asimetría de estos datos, ¿Qué medida de tendencia central resume mejor los kilogramos de <span class="math inline">\(CO_2\)</span> emisiones por persona por año para el arroz?</p>
<ul>
<li><p>Media</p></li>
<li><p>Mediana</p></li>
<li><p>Ambos la media y la mediana</p></li>
</ul>
<p>Viendo la asimetría de los datos de nuestro último histograma, la medida de tendencia central que mejor resume los kilogramos de CO2 emisiones por persona será o es la mediana.</p>
</section>
<section id="medidas-de-propagación" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="medidas-de-propagación"><span class="header-section-number">1.8</span> Medidas de Propagación</h2>
<p>En esta sección, hablaremos sobre otro conjunto de estadísticas resumidas: Medidas de propagación.</p>
<section id="qué-es-spread" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="qué-es-spread"><span class="header-section-number">1.8.1</span> ¿Qué es Spread?</h3>
<p><img src="fig8.png" class="img-fluid"></p>
<p>Spread es exactamente lo que parece: describe que tan separados o cerca están los puntos de datos. Al igual que las medias del centro, hay algunas medidas diferentes de extensión.</p>
</section>
<section id="la-varianza" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="la-varianza"><span class="header-section-number">1.8.2</span> La Varianza</h3>
<p>La primera medida, la varianza, mide la distancia promedio desde cada punto de datos hasta la media de los datos.</p>
<p><img src="fig9.png" class="img-fluid"></p>
<p>Para calcular la varianza, comenzamos calculando la distancia entre cada punto y la media, por lo que obtenemos un número para cada punto de datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>dists <span class="ot">&lt;-</span> msleep<span class="sc">$</span>sleep_total <span class="sc">-</span> <span class="fu">mean</span>(msleep<span class="sc">$</span>sleep_total)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>dists</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1.66626506  6.56626506  3.96626506  4.46626506 -6.43373494  3.96626506
 [7] -1.73373494 -3.43373494 -0.33373494 -7.43373494 -5.13373494 -1.03373494
[13] -0.43373494  2.06626506 -0.13373494 -2.13373494 -1.33373494  6.96626506
[19] -5.13373494  7.56626506 -6.53373494  9.26626506 -7.53373494 -7.33373494
[25] -0.33373494  0.46626506  4.46626506  2.06626506 -0.63373494 -8.53373494
[31] -7.73373494 -4.23373494 -4.13373494 -2.43373494 -0.93373494 -7.13373494
[37]  8.96626506 -0.33373494  3.76626506  3.86626506  2.36626506  2.06626506
[43]  9.46626506  4.16626506  0.56626506 -2.73373494  4.06626506 -2.03373494
[49] -6.63373494 -0.73373494  5.36626506 -0.03373494  3.06626506 -1.03373494
[55] -0.13373494  0.56626506  1.06626506  3.26626506 -6.93373494 -4.83373494
[61]  0.66626506  7.66626506 -5.03373494  2.56626506 -1.73373494 -0.83373494
[67] -2.03373494  0.86626506  0.16626506  6.16626506  3.36626506  5.46626506
[73]  2.36626506 -1.33373494 -1.83373494  5.36626506 -6.03373494  5.16626506
[79] -1.53373494 -5.23373494 -4.13373494  2.06626506 -0.63373494</code></pre>
</div>
</div>
<p>Luego elevamos al cuadrado cada distancia y luego las sumamos todas juntasd.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>squared_dists <span class="ot">&lt;-</span> (dists)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>squared_dists</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  2.776439251 43.115836841 15.731258528 19.947523588 41.392945275
 [6] 15.731258528  3.005836841 11.790535637  0.111379010 55.260415155
[11] 26.355234432  1.068607926  0.188125998  4.269451299  0.017885034
[16]  4.552824793  1.778848890 48.528848890 26.355234432 57.248366962
[21] 42.689692263 85.863668167 56.757162143 53.783668167  0.111379010
[26]  0.217403106 19.947523588  4.269451299  0.401619974 72.824632022
[31] 59.810656118 17.924511540 17.087764552  5.923065757  0.871860938
[36] 50.890174191 80.393909130  0.111379010 14.184752504 14.948005516
[41]  5.599210335  4.269451299 89.610174191 17.357764552  0.320656118
[46]  7.473306721 16.534511540  4.136077805 44.006439251  0.538366962
[51] 28.796800697  0.001138046  9.401981420  1.068607926  0.017885034
[56]  0.320656118  1.136921179 10.668487444 48.076680215 23.364993468
[61]  0.443909130 58.771619974 25.338487444  6.585716359  3.005836841
[66]  0.695113950  4.136077805  0.750415155  0.027644070 38.022824793
[71] 11.331740456 29.880053709  5.599210335  1.778848890  3.362583829
[76] 28.796800697 36.405957323 26.690294673  2.352342865 27.391981420
[81] 17.087764552  4.269451299  0.401619974</code></pre>
</div>
</div>
<p>Finalmente, dividimos la suma de las distancias al cuadrado por el número de puntos de datos menos 1, lo que nos da la varianza.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>sum_sq_dists <span class="ot">&lt;-</span> <span class="fu">sum</span>(squared_dists)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sum_sq_dists</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1624.066</code></pre>
</div>
</div>
<p>Cuanto mayor es la varianza, más dispersos están los datos. Es importante tener en cuenta que las unidades de varianza están al cuadrado, por lo que en este caso son 19.8 horas al cuadrado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>sum_sq_dists<span class="sc">/</span><span class="dv">82</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.80568</code></pre>
</div>
</div>
<p><br>
Podemos calcular la varianza en un solo paso usando la función <code>var</code> de R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(msleep<span class="sc">$</span>sleep_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.80568</code></pre>
</div>
</div>
</section>
</section>
<section id="desviación-estándar" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="desviación-estándar"><span class="header-section-number">1.9</span> Desviación Estándar</h2>
<p>La desviación estándar es otra medida de dispersión, calculada tomando la raíz cuadrada de la varianza. En R se usa la función <code>std</code> para su obtención. Lo bueno de la desviación estándar es que las unidades suelen ser más faciles de entender ya que no están elevadas al cuadrado. Es mejor pensar en 4 horas y media que en 19.8 horas al cuadrado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(msleep<span class="sc">$</span>sleep_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.450357</code></pre>
</div>
</div>
<section id="desviación-absoluta-media" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="desviación-absoluta-media"><span class="header-section-number">1.9.1</span> Desviación Absoluta Media</h3>
<p>La desviación absoluta media toma el valor absoluto de las distancias a la media y luego toma la media de esas diferencias. Si bien esto es similar a la desviación estándar, no es exactamente lo mismo. La desviación estándar eleva al cuadrado las distancias, por lo que las distancias más largas penalizan más que las más cortas, mientras que la desviación media absoluta penaliza cada distancia por igual. Uno no es mejor que el otro, pero <code>sd</code> es más común que <code>mad</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>dists <span class="ot">&lt;-</span> msleep<span class="sc">$</span>sleep_total <span class="sc">-</span> <span class="fu">mean</span>(msleep<span class="sc">$</span>sleep_total)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(dists))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.566701</code></pre>
</div>
</div>
</section>
<section id="cuartiles" class="level3" data-number="1.9.2">
<h3 data-number="1.9.2" class="anchored" data-anchor-id="cuartiles"><span class="header-section-number">1.9.2</span> Cuartiles</h3>
<p>Antes de discutir la siguiente medida de dispersión, hablemos rapidamente sobre los cuartiles. Los cuartiles dividen los datos en cuatro partes iguales. Aquí llamamos a la función <code>quantile()</code> para obtener los cuartiles de los datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   25%   50%   75%  100% 
 1.90  7.85 10.10 13.75 19.90 </code></pre>
</div>
</div>
<p>Esto significa que el 25% de los datos estan entre 1.9 y 7.85, otro 25% de los datos está entre 7.85 y 10.10, y así sucesivamente. Esto significa que el segundo cuartil divide los datos en dos, con el 50% de los datos debajo y el 50% de los datos, arriba, por lo que es exactamente igual que la mediana.</p>
</section>
<section id="gráficas-de-caja-usan-cuartiles" class="level3" data-number="1.9.3">
<h3 data-number="1.9.3" class="anchored" data-anchor-id="gráficas-de-caja-usan-cuartiles"><span class="header-section-number">1.9.3</span> Gráficas de caja usan cuartiles</h3>
<p>Las cajas en los diagramas de cajas representan cuartiles. La parte inferior de la caja es el primer cuartil y la parte superior de la caja es el tercer cuartil. La linea media es el segundo cuartil, o la mediana.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(msleep, <span class="fu">aes</span>(<span class="at">y =</span> sleep_total)) <span class="sc">+</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="intro_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="cuantiles" class="level3" data-number="1.9.4">
<h3 data-number="1.9.4" class="anchored" data-anchor-id="cuantiles"><span class="header-section-number">1.9.4</span> Cuantiles</h3>
<p>Los cuantiles, también llamados percentiles, son una versión generalizada del cuartil, por lo que pueden dividir los datos en 5 partes o diez partes, por ejemplo. De forma predeterminada la función quantile devuelve los cuartiles de los datos, pero podemos ajustar esto usando el argumento <code>probs</code> , que toma un vector de proporciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.2</span>, <span class="fl">0.4</span>, <span class="fl">0.6</span>, <span class="fl">0.8</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   20%   40%   60%   80%  100% 
 1.90  6.24  9.48 11.14 14.40 19.90 </code></pre>
</div>
</div>
<p>Aquí, dividimos los datos en cinco partes iguales. También podemos usar la función <code>seq(from, to, by)</code> como atajo, que toma el número más bajo, el número más alto y el número por el que queremos saltar. Podemos calcular los mismos cuantiles usando <code>seq</code> de cero a uno, saltando de 0.2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   20%   40%   60%   80%  100% 
 1.90  6.24  9.48 11.14 14.40 19.90 </code></pre>
</div>
</div>
</section>
</section>
<section id="rango-intercuartilico-iqr" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="rango-intercuartilico-iqr"><span class="header-section-number">1.10</span> Rango Intercuartilico (IQR)</h2>
<p>El rango intercuartilico, o IQR, es otra medida de dispersión. Es la distancia entre los percentiles 25 y 75 que también es la altura de la caja en un diagrama de caja. Podemos calcularlo usando la función cuantil para obtener 5.9 horas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="fl">0.75</span>) <span class="sc">-</span> <span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="fl">0.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>75% 
5.9 </code></pre>
</div>
</div>
<section id="valores-atípicos" class="level3" data-number="1.10.1">
<h3 data-number="1.10.1" class="anchored" data-anchor-id="valores-atípicos"><span class="header-section-number">1.10.1</span> Valores atípicos</h3>
<p>Los valores atípicos son puntos de datos que son sustancialmente diferentes de los demás. Pero, ¿cómo sabemos qué es una diferencia sustancial? Una regla que se usa a menudo es que cualquier punto de datos menor que el primer cuartil menos 1.5 veces el IQR es un valor atípico. Así como cualquier punto mayor que el tercer cuartil más 1.5 veces el IQR.</p>
<ul>
<li><p><span class="math inline">\(data &lt; Q_1 - 1.5\times IQR\)</span></p></li>
<li><p><span class="math inline">\(data &gt; Q_3 + 1.5\times IQR\)</span></p></li>
</ul>
</section>
<section id="encontrar-valores-atípicos" class="level3" data-number="1.10.2">
<h3 data-number="1.10.2" class="anchored" data-anchor-id="encontrar-valores-atípicos"><span class="header-section-number">1.10.2</span> Encontrar valores atípicos</h3>
<p>Para encontrar valores atípicos, comenzaremos calculando el IQR de los pesos corporales de los mamiferos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>iqr <span class="ot">&lt;-</span> <span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total,<span class="fl">0.75</span>) <span class="sc">-</span> <span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="fl">0.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Luego podemos calcular los umbrales inferior y superior siguiendo las fórmulas de la diapositiva anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>lower_threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="fl">0.25</span>) <span class="sc">-</span> <span class="fl">1.5</span><span class="sc">*</span>iqr</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>upper_threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(msleep<span class="sc">$</span>sleep_total, <span class="fl">0.75</span>) <span class="sc">+</span> <span class="fl">1.5</span><span class="sc">*</span>iqr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora podemos filtrar el marco de datos para encontrar mamiferos cuyo peso corporal esta por encima o por debajo de los umbrales.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>msleep <span class="sc">%&gt;%</span> <span class="fu">filter</span>(bodywt <span class="sc">&lt;</span> lower_threshold <span class="sc">|</span> bodywt <span class="sc">&gt;</span> upper_threshold) <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, vore, sleep_total, bodywt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 4
   name           vore  sleep_total bodywt
   &lt;chr&gt;          &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 Cheetah        carni        12.1   50  
 2 Cow            herbi         4    600  
 3 Goat           herbi         5.3   33.5
 4 Asian elephant herbi         3.9 2547  
 5 Horse          herbi         2.9  521  
 6 Donkey         herbi         3.1  187  
 7 Giraffe        herbi         1.9  900. 
 8 Pilot whale    carni         2.7  800  
 9 Gray seal      carni         6.2   85  
10 Human          omni          8     62  
# ℹ 13 more rows</code></pre>
</div>
</div>
<p>Podemos ver que hay 23 valores atípicos de peso corporal en este conjunto de datos, incluidos la vaca y el elefante asiático.</p>
</section>
</section>
<section id="ejercicio-3" class="level2" data-number="1.11">
<h2 data-number="1.11" class="anchored" data-anchor-id="ejercicio-3"><span class="header-section-number">1.11</span> Ejercicio 3</h2>
<p>Los cuantiles ya sabemos que son una excelente manera de resumir datos numéricos, ya que se pueden usar para medir el centro y la dispersión, así como para tener una idea de dónde se encuentra un punto de datos en relación con el resto del conjunto de datos. Por ejemplo, es posible que desee otorgar un descuento al 10% de los usuarios más activos en un sitio web.</p>
<p>En este ejercicio, calculará cuartiles, quantiles y deciles, que dividen un conjunto de datos en 4, 5 y 10 partes, respectivamente.</p>
<p>Primero calculemos los cuartiles de la columna <code>co2_emssion</code> de <code>food_consumption</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(food_consumption<span class="sc">$</span>co2_emission)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       0%       25%       50%       75%      100% 
   0.0000    5.2100   16.5300   62.5975 1712.0000 </code></pre>
</div>
</div>
<p>Calculamos ahora, los seis cuantiles que dividen los datos en 5 partes (quantiles) de la columna <code>co2_emission</code> de <code>food_consumption</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(food_consumption<span class="sc">$</span>co2_emission, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      0%      20%      40%      60%      80%     100% 
   0.000    3.540   11.026   25.590   99.978 1712.000 </code></pre>
</div>
</div>
<p>Por último, calculamos los once cuantiles de <code>co2_emission</code> esa división de los datos en diez partes (deciles).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(food_consumption<span class="sc">$</span>co2_emission, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      0%      10%      20%      30%      40%      50%      60%      70% 
   0.000    0.668    3.540    7.040   11.026   16.530   25.590   44.271 
     80%      90%     100% 
  99.978  203.629 1712.000 </code></pre>
</div>
</div>
</section>
<section id="ejercicio-4" class="level2" data-number="1.12">
<h2 data-number="1.12" class="anchored" data-anchor-id="ejercicio-4"><span class="header-section-number">1.12</span> Ejercicio 4</h2>
<p>Ya vio previamente que la varianza y la desviación estándar son dos de las formas más comunes de medir la dispersión de una variable, y practicaremos su cálculo en este ejercicio. La difusión es importante ya que puede ayudar a informar las expectativas. Por ejemplo, si un vendedor vende una media de 20 productos al día, pero tiene una desviación estándar de 10 productos, probablemente habrá días en los que solo venderá uno o dos. Información como esta es importante, especialmente cuando se hacen predicciones.</p>
<p>Para este ejericio, primer calcularemos la varianza y la desviación estándar de <code>co2_emission</code> para cada una de las <code>food_category</code> agrupando por y resumiendo la varianza como <code>var_co2</code> y la desviación estándar como <code>sd_co2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>food_consumption <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(food_category) <span class="sc">%&gt;%</span> </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">var_co2 =</span> <span class="fu">var</span>(co2_emission),</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">sd_co2 =</span> <span class="fu">sd</span>(co2_emission))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   food_category   var_co2  sd_co2
   &lt;fct&gt;             &lt;dbl&gt;   &lt;dbl&gt;
 1 beef          88748.    298.   
 2 eggs             21.4     4.62 
 3 fish            922.     30.4  
 4 lamb_goat     16476.    128.   
 5 dairy         17672.    133.   
 6 nuts             35.6     5.97 
 7 pork           3095.     55.6  
 8 poultry         245.     15.7  
 9 rice           2281.     47.8  
10 soybeans          0.880   0.938
11 wheat            71.0     8.43 </code></pre>
</div>
</div>
<p>Luego, creemos un histograma de <code>co2_emission</code> para cada una de <code>food_category</code> usando <code>facet_wrap()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(food_consumption, <span class="fu">aes</span>(co2_emission)) <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creación del  histograma</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creamos subgráficos separados para cada categoría de food_category</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> food_category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="intro_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Excelente medición de dispersión! La carne de res tiene la mayor cantidad de variación en sus emisiones de CO2, mientras que los huevos, las nueces y la soya tienen cantidades relativamente pequeñas de variación.</p>
</section>
<section id="ejercicio-5" class="level2" data-number="1.13">
<h2 data-number="1.13" class="anchored" data-anchor-id="ejercicio-5"><span class="header-section-number">1.13</span> Ejercicio 5</h2>
<p>Los valores atípicos pueden tener grandes efectos en las estadísticas como la media, así como en las estadísticas que se basan en la media, como la varianza y la desviación estándar. El rango intercuartilico, o IQR, es otra forma de medir la dispersión que está menos influenciada por los valores atípicos. IQR también se usa a menudo para encontrar valores atípicos. Si un valor es menor que <span class="math inline">\(Q_1 - 1.5\times IQR\)</span> o mayor que <span class="math inline">\(Q_3 + 1.5\times IQR\)</span>, se considera un valor atípico. De hecho, así es como <code>ggplot2</code> se calculan las longitudes de los bigotes en un diagrama de caja.</p>
<p><img src="fig10.png" class="img-fluid"></p>
<p>En este ejercicio, calcularemos IQR y lo utilizaremos para encontrar algunos valores atípicos.</p>
<p>Primero calculamos el total de <code>co2_emission</code> por país agrupando por país y tomando la suma de <code>co2_emission</code>. Llamaremos a la suma <code>total_emission</code> y almacenaremos el marco de datos resultante como <code>emission_by_country</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>emissions_by_country <span class="ot">&lt;-</span> food_consumption <span class="sc">%&gt;%</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_emission =</span> <span class="fu">sum</span>(co2_emission))</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>emissions_by_country <span class="sc">%&gt;%</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  country   total_emission
  &lt;chr&gt;              &lt;dbl&gt;
1 Albania            1778.
2 Algeria             708.
3 Angola              413.
4 Argentina          2172.
5 Armenia            1110.
6 Australia          1939.</code></pre>
</div>
</div>
<p>Ahora, calcularemos el primer y tercer cuartil de <code>total_emission</code> y lo guardamos como <code>q1</code> y <code>q3</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(emissions_by_country<span class="sc">$</span>total_emission, <span class="fl">0.25</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(emissions_by_country<span class="sc">$</span>total_emission, <span class="fl">0.75</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>iqr <span class="ot">&lt;-</span> q3<span class="sc">-</span>q1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Luego, calculamos los puntos de corto inferior y superior para los valores atípicos de <code>total_emission</code> y guardamos como <code>lower</code> y <code>upper</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> q1<span class="fl">-1.5</span><span class="sc">*</span>iqr</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> q3<span class="fl">+1.5</span><span class="sc">*</span>iqr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Usamos <code>filter()</code> para obtener países con un límite <code>total_emission</code> superior o inferior al límite. <code>upper</code> <code>total_emission</code> <code>lower</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>emissions_by_country <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_emission <span class="sc">&lt;</span> lower <span class="sc">|</span> total_emission <span class="sc">&gt;</span> upper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  country   total_emission
  &lt;chr&gt;              &lt;dbl&gt;
1 Argentina          2172.</code></pre>
</div>
</div>
<p>Como puede ver, parece que Argentina tiene una cantidad sustancialmente mayor de emisiones de CO2 por persona que otros países del mundo.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introducción</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Números aleatorios y Probabilidad</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>